APM-3001 Fail spec pipeline if not master but no pr

diff --git a/.github/workflows/spec-release-pipeline.yml b/.github/workflows/spec-release-pipeline.yml
--- a/.github/workflows/spec-release-pipeline.yml
+++ b/.github/workflows/spec-release-pipeline.yml
@@ -17,6 +17,21 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
+      
+      - name: Get Pull Request Number
+        id: pr
+        if: github.ref != 'refs/heads/master'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          pr_number=$(gh pr view --json number -q .number || echo "")
+          if test -z "$pr_number"
+          then
+                echo "Pipeline can't be run on branch other than master without PR number"
+                exit 1
+          else
+                echo PR number - $pr_number
+          fi
 
       - name: Install Python 3.8
         uses: actions/setup-python@v1
